#' Summary method for twostage objects
#'
#' Provides a summary for objects of class "twostage".
#'
#' @param object An object of class "twostage".
#' @param ... Additional arguments (currently not used).
#' @return The summary of the "twostage" object.
#' @exportMethod summary
#'
setMethod(
  "summary", "twostage",
  function(object, ...) {
    if (!inherits(object, "twostage")) {
      stop("This does not appear to be an object generated by twostage()!")
    }

    # create a table of estimates and ses, including naive ses and TSML ses
    TS_table <- parameterEstimates_ts(object, naive.se = TRUE)

    # create a sentence with test statistic results to print
    Tres <- object@twostage$test
    df <- object@twostage$df
    pval <- object@twostage$pval
    colnames(Tres) <- "Tres"
    colnames(pval) <- "pval"
    df <- as.matrix(df)
    colnames(df) <- "df"

    # summary list
    summary_list <- list(
      TS_table = TS_table,
      Tres = Tres,
      pval = pval,
      df = df
    )

    # Assign the class for method dispatch
    class(summary_list) <- "SummaryTwostage"

    summary_list
  }
)

#' Print method for SummaryTwostage objects
#'
#' @param x An object of class 'SummaryTwostage'
#' @param ... Additional arguments (currently not used)
#' @export
print.SummaryTwostage <- function(x, ...) {
  # Create a rounded table of estimates for display
  TS_table_round <- as.data.frame(lapply(x$TS_table, function(column) {
    if (is.numeric(column)) round(column, 3) else column
  }))

  # Test statistic values
  Tres <- x$Tres
  df <- x$df
  pval <- x$pval

  if (!is.null(Tres)) {
    test.output <- paste(
      "The residual-based TSML chi-square is", round(Tres, 3),
      "against", df, "degrees of freedom, with a p-value of",
      round(pval, 3)
    )
  } else {
    test.output <- paste("The residual-based TSML chi-square could not be computed.")
  }

  cat("Summary of Two-Stage Analysis \n")
  cat("----------------------------\n")
  cat(
    "Parameter estimates from Stage 2, naive standard errors from lavaan",
    "(with z-test and p-value),\n", "and the corrected TSML standard errors",
    "(with z-test and p-value): \n"
  )
  print(TS_table_round, quote = FALSE, row.names = FALSE)
  cat("----------------------------\n")
  cat(test.output, "\n")
}
